# Generated by Django 2.1.7 on 2019-03-25 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('key', models.TextField()),
                ('revoked', models.BooleanField(default=False)),
                ('serial', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is521_ca.User'),
        ),
    ]
